source_roots = ["."]

[[modules]]
path = "app.domain"
depends_on = []

[[modules]]
path = "app.application"
depends_on = [
    { path = "app.domain" },
]

[[modules]]
path = "app.infrastructure"
depends_on = [
    { path = "app.domain" },
    { path = "app.application" },
]

[[modules]]
path = "app.presentation"
depends_on = [
    { path = "app.domain" },
    { path = "app.application" },
]
